---
title: "[Rust编程第一课]-09 基础篇08-数据结构：错误处理"
date: 2023-04-20T11:00:00+08:00
lastmod: 2023-04-20T16:00:00+08:00
author: nange
draft: false
description: "Rust编程第一课 基础部分"

categories: ["programming"]
series: ["rust-first-class"]
series_weight: 9
tags: ["rust"]
---

## 错误处理的主流方法

### 返回错误码

* C语言的例子：

  ```c
  size_t fread(void *ptr, size_t size, size_t nmemb, FILE *stream)
  ```

  * 如果返回的 size_t 和传入的 size_t 不一致，那么要么发生了错误，要么是读到文件尾（EOF），调用者要进一步通过 ferror 才能得到更详细的错误。

  * 像 C 这样，通过返回值携带错误信息，有很多局限。返回值有它原本的语义，强行把错误类型嵌入到返回值原本的语义中，需要全面且实时更新的文档，来确保开发者能正确区别对待，正常返回和错误返回。

* Go语言做了改进，可以返回单独的错误对象：

  ```go
  func Fread(file *File, b []byte) (n int, err error)
  ```

  但是使用返回值的方式，始终有个致命的问题：**在调用者调用时，错误就必须得到处理或者显式的传播。**

  这样写出来的代码会非常冗长，对我们开发者的用户体验不太好。如果不处理，又会丢掉这个错误信息，造成隐患。

* 另外，**大部分生产环境下的错误是嵌套的**。这样的嵌套错误在 C / Golang 都是很难完美表述。

### 使用异常

* 返回值不利于错误的传播，Java 等很多语言使用异常来处理错误

* 可以把异常看成一种关注点分离（Separation of Concerns）：错误的产生和错误的处理完全被分隔开，调用者不必关心错误，而被调者也不强求调用者关心错误

* 但使用异常的心智负担也很高：这个过程远比想象的复杂，而且需要额外操心异常安全（exception safety）。如下的切换背景图片伪代码：

  ```java
  void transition(...) {
    lock(&mutex);
    delete background;
    ++changed;
    background = new Background(...);
    unlock(&mutex);
  }
  ```

  如果在创建新的背景时失败，抛出异常，会跳过后续的处理流程，一路栈回溯到 `try catch` 的代码，那么，这里锁住的 `mutex` 无法得到释放，而已有的背景被清空，新的背景没有创建，程序进入到一个奇怪的状态。

* 异常处理另外一个比较严重的问题是：开发者会滥用异常。只要有错误，不论是否严重、是否可恢复，都一股脑抛个异常。到了需要的地方，捕获一下了之。殊不知，异常处理的开销要比处理返回值大得多，滥用会有很多额外的开销。

### 使用类型系统

* **通过类型来表征错误，使用一个内部包含正常返回类型和错误返回类型的复合类型，通过类型系统来强制错误的处理和传递**。
* 这种方法依旧是通过返回值返回错误，但是错误被包裹在一个完整的、必须处理的类型中，比 Golang 的方法更安全。
* 使用返回值返回错误的一大缺点是：错误需要被调用者立即处理或者显式传递。但是使用类型来处理错误的好处是，我们可以用函数式编程的方法简化错误的处理，比如 `map`、`fold` 等函数，让代码相对不那么冗余。
* 很多不可恢复的错误，如“磁盘写满，无法写入”的错误，使用异常处理可以避免一层层传递错误，让代码简洁高效，所以大多数使用类型系统来处理错误的语言，会同时使用异常处理作为补充。

## Rust的错误处理

### Option和Result

* `Option`是一个enum，定义如下：

  ```rust
  pub enum Option<T> {
      None,
      Some(T),
  }
  ```

  它可以承载有值 / 无值这种最简单的错误类型。

* `Result` 是一个更加复杂的 enum，定义如下：

  ```rust
  #[must_use = "this `Result` may be an `Err` variant, which should be handled"]
  pub enum Result<T, E> {
      Ok(T),
      Err(E),
  }
  ```

  * 当函数出错时，可以返回 `Err(E)`，否则 `Ok(T)`。

  * `Result` 类型声明时还有个 `must_use` 的标注，编译器会对有 `must_use` 标注的所有类型做特殊处理：如果该类型对应的值没有被显式使用，则会告警。这样，保证错误被妥善处理。如下图所示：

    ![img](/images/e2100e3f17a9587c4d4bf50523c10653.png)

    这虽然可以极大避免遗忘错误的显示处理，但如果我们并不关心错误，只需要传递错误，还是会写出像 C 或者 Golang 一样比较冗余的代码。怎么办？

### ? 操作符

* 好在 Rust 除了有强大的类型系统外，还具备元编程的能力。早期 Rust 提供了 `try!` 宏来简化错误的显式处理，后来为了进一步提升用户体验，`try!` 被进化成 `?` 操作符。如下例子：

  ```rust
  use std::fs::File;
  use std::io::Read;
  
  fn read_file(name: &str) -> Result<String, std::io::Error> {
    let mut f = File::open(name)?;
    let mut contents = String::new();
    f.read_to_string(&mut contents)?;
    Ok(contents)
  }
  ```

  通过 `?` 操作符，Rust 让错误传播的代价和异常处理不相上下，同时又避免了异常处理的诸多问题。

* `?` 操作符内部被展开成类似这样的代码：

  ```rust
  match result {
    Ok(v) => v,
    Err(e) => return Err(e.into())
  }
  ```

  所以，我们可以方便地写出类似这样的代码，简洁易懂，可读性很强：

  ```rust
  fut
    .await?
    .process()?
    .next()
    .await?;
  ```

* 虽然 `?` 操作符使用起来非常方便，但不同的错误类型之间是无法直接使用，需要实现 `From` trait 在二者之间建立起转换的桥梁，这会带来额外的麻烦。稍后给出解决方案。

### 函数式错误处理

* Rust 还为 `Option` 和 `Result` 提供了大量的辅助函数，如 `map / map_err / and_then`，可以很方便地处理数据结构中各种情况。如下图所示：

  ![img](/images/0c3ae02cc6d8994e500fc02385a605e0.jpg)

* 通过这些函数，可以很方便地对错误处理引入 [Railroad oriented programming](https://www.slideshare.net/ScottWlaschin/railway-oriented-programming) 范式。

  比如用户注册的流程，需要校验用户输入，对数据进行处理，转换，然后存入数据库中。可以这么撰写这个流程：

  ```rust
  Ok(data)
    .and_then(validate)
    .and_then(process)
    .map(transform)
    .and_then(store)
    .map_error(...)
  ```

  执行流程如下图：

  ![img](/images/fdbbbee8e125205efd00f8648fc8b04c.jpg)

* 此外，`Option` 和 `Result` 的互相转换也很方便，这也得益于 Rust 构建的强大的函数式编程的能力。如：

  * 从 `Option` 转换为 `Result`：

    ```rust
    let some_value: Option<i32> = Some(42);
    let none_value: Option<i32> = None;
    
    let result_from_some: Result<i32, &str> = some_value.ok_or("None value found");
    let result_from_none: Result<i32, &str> = none_value.ok_or("None value found");
    ```

  * 从 `Result` 转换为 `Option`：

    ```rust
    let ok_value: Result<i32, &str> = Ok(42);
    let err_value: Result<i32, &str> = Err("Error occurred");
    
    let option_from_ok: Option<i32> = ok_value.ok();
    let option_from_err: Option<i32> = err_value.ok();
    ```

* 无论是通过 `?` 操作符，还是函数式编程进行错误处理，Rust 都力求让错误处理灵活高效，让开发者使用起来简单直观。

### panic! 和 catch_unwind

* 一旦需要抛出异常，那抛出的一定是严重的错误。所以，Rust 跟 Golang 一样，使用了诸如 `panic!` 这样的字眼警示开发者：想清楚了。

* 在使用 `Option` 和 `Result` 类型时，开发者也可以对其 `unwarp()` 或者 `expect()`，强制把 `Option` 和 Result` 转换成 `T`，如果无法完成这种转换，也会 `panic!` 出来。

* 一般而言，`panic!` 是不可恢复或者不想恢复的错误，我们希望在此刻，程序终止运行并得到崩溃信息。

* 有些场景下，我们也希望能够像异常处理那样能够栈回溯。Rust 标准库下提供了 `catch_unwind()` ，把调用栈回溯到 `catch_unwind` 这一刻，作用和其它语言的 `try {…} catch {…}` 一样。如下代码：

  ```rust
  use std::panic;
  
  fn main() {
      let result = panic::catch_unwind(|| {
          println!("hello!");
      });
      assert!(result.is_ok());
      let result = panic::catch_unwind(|| {
          panic!("oh no!");
      });
      assert!(result.is_err());
      println!("panic captured: {:#?}", result);
  }
  ```

  

### Error trait 和错误类型的转换

* `Result<T, E>` 里 `E` 代表错误的数据类型。为了规范数据类型的行为，Rust 定义了 `Error` trait：

  ```rust
  pub trait Error: Debug + Display {
      fn source(&self) -> Option<&(dyn Error + 'static)> { ... }
      fn backtrace(&self) -> Option<&Backtrace> { ... }
      fn description(&self) -> &str { ... }
      fn cause(&self) -> Option<&dyn Error> { ... }
  }
  ```

* 我们可以定义我们自己的数据类型，然后为其实现 `Error` trait。

* 不过，这样的工作已经有人替我们简化了：**可以使用 `thiserror`和 `anyhow`来简化这个步骤**。

  * `thiserror` 提供了一个派生宏（`derive macro`）来简化错误类型的定义，比如：

    ```rust
    use thiserror::Error;
    #[derive(Error, Debug)]
    #[non_exhaustive]
    pub enum DataStoreError {
        #[error("data store disconnected")]
        Disconnect(#[from] io::Error),
        #[error("the data for key `{0}` is not available")]
        Redaction(String),
        #[error("invalid header (expected {expected:?}, found {found:?})")]
        InvalidHeader {
            expected: String,
            found: String,
        },
        #[error("unknown data store error")]
        Unknown,
    }
    ```

    如果在撰写一个 Rust 库，那么 `thiserror` 可以很好地协助对这个库里所有可能发生的错误进行建模。

  * `anyhow` 实现了 `anyhow::Error` 和任意符合 `Error` trait 的错误类型之间的转换，可以使用 `?` 操作符，不必再手工转换错误类型。`anyhow` 还可以很容易地抛出一些临时的错误，而不必费力定义错误类型，当然，不提倡滥用这个能力。



















